url: http://example.com
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock]
permalink: pretty
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-feed
author:
  twitter: CounterBug
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge